# Generated by Django 5.0.7 on 2025-02-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_email_verified_user_google_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("client", "Client")],
                default="client",
                max_length=10,
            ),
        ),
    ]
